version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/bq-backup-and-restore"
    labels:
      - "dependencies"
    schedule:
      interval: "daily"
    groups:
      patch-updates:
        update-types:
          - "patch"
      non-patch-updates:
        update-types:
          - "minor"
          - "major"
    commit-message:
      prefix: "chore: "
    target-branch: "master"

  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependencies"
    schedule:
      interval: "daily"
    groups:
      patch-updates:
        update-types:
          - "patch"
      non-patch-updates:
        update-types:
          - "minor"
          - "major"
    commit-message:
      prefix: "chore: "
    target-branch: "master"
